name: Compile PHP Extension

on:
  push:

jobs:
  build:

    strategy:
      matrix:
        os: [macos-latest]
        php: [8.1]

    runs-on: ${{ matrix.os }}

    env:
      LDFLAGS: "-L/opt/homebrew/opt/ncurses/lib"
      CPPFLAGS: "-I/opt/homebrew/opt/ncurses/include"
      PKG_CONFIG_PATH: "/opt/homebrew/opt/ncurses/lib/pkgconfig"
      CFLAGS: "-Dulong=unsigned long"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ncurses
        run: |
          brew install ncurses

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: PHPize
        run: phpize

      - name: Configure
        run: ./configure --with-ncurses=/opt/homebrew/opt/ncurses --enable-ncursesw

      - name: Make
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-php-${{ matrix.php }}-ext-ncurses
          path: modules/*.so
