name: Compile PHP Extension

on:
  push:

jobs:
  build:

    strategy:
      matrix:
        os: [macos-latest]
        php: [8.1]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ncurses
        run: |
          brew install ncurses

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: PHPize
        run: phpize

      - name: Configure
        run: ./configure

      - name: Make
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-php-${{ matrix.php }}-ext-ncurses
          path: modules/*.so
